#ifndef _DEFINES_H_
#define _DEFINES_H_
#define SETBIT(WORD,BITPOS) (WORD|=1<<BITPOS)
#define CLRBIT(WORD,BITPOS) (WORD|=~(1<<BITPOS))
#define SSETBIT(WORD,BITPOS) (WORD =1<<BITPOS)
#define SCLRBIT(WORD,BITPOS) (WORD =1<<BITPOS)
#define WBYTE(WORD,SBITPOS,BYTE) (WORD = (WORD &~(0XFF<<SBITPOS))|(BYTE<<SBITPOS))
#define WBIT (WORD,BITPOS,BIT) (WORD =(WORD &~(1<<BITPOS))|(BIT<<BITPOS))
#define RBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
#define RNIBBLE(WORD,SBITPOS) ((WORD>>SBITPOS)&15)
#define WNIBBLE(WORD,SBITPOS,NIBBLE) WORD=(WORD &~(0XFF<<SBITPOS))|(NIBBLE<<SBITPOS)
#define RBYTE(WORD,SBITPOS) ((WORD>>SBITPOS)&255)
#define CPLBIT(WORD,BITPOS) (WORD ^=1<<BITPOS)
#define READWRITEBIT(DWORD,DBIT,SBIT) \
(DWORD=DWORD &~(1<<DBIT)|(((DWORD>>SBIT)&1)<<DBIT))
#define READWRITEBIT2(DWORD,DBIT,SWORD,SBIT) \
(DWORD=(DWORD &~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))
#endif
